// console.log(true);
// console.log(false)
//
// console.log(3 < 1 || 100);
//
// // console.log(100 > 2 || false);
//
// console.log('孔中由' && 100)
// console.log('' || 0)
//
// let a = 22
// let b = 43
// let result = a > 100 ? b = 666 : b = 33
// console.log(result)

//
// for (let i = 0; i < 101; i++) {
//     if (i % 2 === 0) {
//         sum += i
//     }
// }
// console.log(sum)
// let sum = 0
// function sum(a, b) {
//     let n = 10
//     let m = 20
//     let total = n + m
//     return (total / 2).toFixed(2)
// }
// let a='10'
// a==10?a++:a--
// console.log(a);

// let i=1
// console.log(5+i++);
// i=1
// console.log(5+(++i));

i=3
console.log(5+(++i)+(i++)+1+(--i)+(i--)-2);
console.log(i);


//4 5 4 3
//9+4+1+4+4-2